"""empty message

Revision ID: 8f3fafb6bfe2
Revises: e069f588dbb5
Create Date: 2025-02-20 10:15:24.192227

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f3fafb6bfe2"
down_revision = "e069f588dbb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.add_column(sa.Column("admin_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_order_user", "user", ["admin_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.drop_constraint("fk_order_user", type_="foreignkey")
        batch_op.drop_column("admin_id")

    # ### end Alembic commands ###
